### ISSUE TITLE
Can't read Tasks from Google Calendar

### ISSUE THREAD

**Issue by bennyvenassi** [ebarooni/capacitor-calendar#103]
Hi,
I'm using your awesome plugin to read events from my Google Calendar on Android.
But the listEventsInRange function only reads events. Tasks wont be fetched.
Is there a way to get tasks, too?

` async listEvents(ids: number[]) {
    try {
      let calEvents = await CapacitorCalendar.listEventsInRange({startDate: Date.now(), endDate: (Date.now() + (52 * 7 * 24 * 60 * 60 * 1000))});
      if (calEvents) {
        let matchingEvents: CalendarEvent[] = [];
       calEvents.result.forEach(calEvent => {
          ids.forEach(id => {
            if (id === +calEvent.calendarId) {
              matchingEvents.push(calEvent);
            }
          });
        });
        return matchingEvents;
      }
    } catch (err) {
      console.error(err);
      return [];
    }
  }`

Thank You

**Comment by ebarooni** [comment]
Hi @bennyvenassi ,

Sadly fetching tasks from google calendar is out of the planned scope of the plugin because of its setup. For fetching tasks you would need to use the Tasks API which needs a google cloud project. This would be something to setup for your app, and not in the plugin. 

Maybe for later I will think of helper methods that can help the communication between the app and the Tasks API. But at this moment I dont see it coming anytime soon.

**Comment by bennyvenassi** [comment]
Thank you @ebarooni for your quick respond.
