### ISSUE TITLE
enhance(README): import & implementation

### ISSUE THREAD

**Issue by rbalet** [ebarooni/capacitor-calendar#140]
## Description
I'm trying to use this library, but I cannot figure it out how to implement it inside my `component.ts` file.

I've tried to look over on [stackoverflow](https://stackoverflow.com/questions/69903484/how-to-add-events-to-the-calendar-of-the-mobile-device-with-ionic-capacitor) and saw that you already tried to help here (Thx for that by the way).

Here an example on how I've tried to use it, but I'm unable to find the correct implementation

![image](https://github.com/user-attachments/assets/b730be14-ed5c-4c3b-9222-645538240b1b)

## Note
Thx a lot for this library, I'm looking forward of using it

**Comment by ebarooni** [comment]
Hi @rbalet thanks for the feedback. The way you are using the plugin is wrong. What you are trying here is to inject the plugin in your component like a service, which does not follow the convention for any capacitor plugin.

You should use the plugin as follows:

```
import { CapacitorCalendar } from '@ebarooni/capacitor-calendar';

export class CalendarService {
  async addEvent() {
    await CapacitorCalendar.createEvent({...});
  }
}
```

For detailed usage check the `/example ` directory of the repo. Also all methods should have inline docs with usage examples.

**Comment by rbalet** [comment]
@ebarooni Sorry, it was dumb of me.

Thx a lot for the quick answer!

**Comment by ebarooni** [comment]
@rbalet Thanks for that! But can you maybe adjust the edit a bit? I believe its not necessary to specifically mention an Angular usage because the usage in React and Vue is the same. Therefore labeling the usage only for Angular might be misleading.

Instead your edit made me notice the code example i have originally provided is wrong. Could you remove the Angular part and edit the original code sample from the answer to:

```
// to open the native prompt
await CapacitorCalendar.createEventWithPrompt({ title: 'My Event' });

// to directly create an event
await CapacitorCalendar.createEvent({ title: 'My Event' });
```
