### ISSUE TITLE
There is no way to add alarms for the event

### ISSUE THREAD

**Issue by akshay030123** [ebarooni/capacitor-calendar#44]
please implement alarms to the add event so that alarm can be triggered if it needs to be for specific events. for example to trigger alarm 10mins, 15 mins, 30mins, before the event.

**Comment by ebarooni** [comment]
@akshay030123 Creating calendar events with options is in the backlog to be implemented. But since finding and deleting events are not yet implemented, they have priority over this. Once those are implemented, this will be next.

**Comment by aparajita** [comment]
> @akshay030123 Creating calendar events with options is in the backlog to be implemented. But since finding and deleting events are not yet implemented, they have priority over this. Once those are implemented, this will be next.

I already implemented alarms, will submit a PR. Do you have an ETA on deleting events, I need that. What about updating an event?

**Comment by ebarooni** [comment]
> > @akshay030123 Creating calendar events with options is in the backlog to be implemented. But since finding and deleting events are not yet implemented, they have priority over this. Once those are implemented, this will be next.
> 
> I already implemented alarms, will submit a PR. Do you have an ETA on deleting events, I need that. What about updating an event?

I would expect to roll out deleteEvents by EOW. But for your PR, if possible i would ask you to wait at least until I have released version 1.0.0 as I have not yet fully defined the project requirements for myself. For updating events I dont have a defined timeline yet. My idea was to first implement create, read and delete so that i know how exactly a calendar event is defined so that i know what could be updated. Therefore the updating events will probably be picked up after delete events is functional.

**Comment by aparajita** [comment]
Hey @ebarooni, the code to add alarms when creating an event is here:

https://github.com/aparajita/capacitor-calendar/commit/695809ce03f3a7977be9137b307b53742f9457e9
