### ISSUE TITLE
Inconsistent/confusing permission constants

### ISSUE THREAD

**Issue by aparajita** [ebarooni/capacitor-calendar#59]
There are a number of inconsistencies with the API I have come across:

- Currently, to request read AND write access on iOS, we use constants called `READ_CALENDAR` and `READ_REMINDERS`. This is quite confusing, since there are constants named `WRITE_CALENDAR` and `WRITE_REMINDERS`, which implies the read constants are in fact **read-only**.

- The API documentation says that the `READ` constants "Represents the permission state for reading", when in fact they represent the permission state for both reading AND writing on iOS. This adds to the confusion.

- Looking at the source code, in the current implementation the reminders constants do nothing (on iOS at least). Full access is requested with either constant.

- On Android, requesting `READ_CALENDAR` permission does NOT provide write permission as well, in contrast to iOS.

#### The fix

I strongly suggest creating a separate set of permission constants for iOS and Android along the lines proposed above, that clearly indicate exactly what the permission is providing.

For example:

`IOS_READ_WRITE_CALENDAR`
`ANDROID_READ_CALENDAR`
`WRITE_ONLY_CALENDAR`  // works the same on both platforms

You may be thinking, "That requires the developer to have separate code for each platform." If we want both read and write permission (without request all permissions), we have to use separate code in any case.

**Comment by aparajita** [comment]
@ebarooni Any thoughts on this?

**Comment by ebarooni** [comment]
@aparajita I see your point and I was actually thinking about your remarks. The problem is the behavior of iOS and Android are slightly different here. on iOS we have write only and full access (which is read and write permissions together). But on Android we have read only and write only.

Im always in the favor of providing exactly the same experience for both iOS and Android (or as much as possible). In this case I found what Android provides, a bit more convenient. Suppose we had defined write only and full access permissions (instead of what is implemented now), a developer on Android that only needs read access (for any reason) is forced to also define and request write access. On the other hand a developer on iOS will not find him or herself in a similar situation.

I would propose the following:

Firstly to provide further information on platform specific behavior of both `readCalendar` and `writeCalendar`. Then to implement two new methods, `requestWriteOnlyCalendarAccess` and `requestFullCalendarAccess` as alternatives to the already existing implementation. Both methods return `Promise<void>` and throw an error if unsuccessful. In this case developers can go for either or mix and match the solutions. Finally over the time either to drop either of the solutions or let both coexist.

For the reminders also you are right. There is less flexibility on iOS and there is in reality only full access or nothing. But i thought I try to match the defined permissions from the calendar by faking them. And finally I propose requestFullRemindersAccess which similarly returns `Promise<void>` and throws an error in case failed.

Let me know what you think about this proposal.

**Comment by aparajita** [comment]
> Im always in the favor of providing exactly the same experience for both iOS and Android

Me too, but Capacitor itself always separates config properties by platform when there is divergent behavior.

> Firstly to provide further information on platform specific behavior of both readCalendar and writeCalendar

The way it is now is creating too many opportunities for mistakes by the developer, because the burden is on them to read and remember every detail of how the constants work on different platforms.

> Then to implement two new methods, requestWriteOnlyCalendarAccess and requestFullCalendarAccess as alternatives to the already existing implementation

You would have to add one more, `requestReadOnlyCalendarAccess`, which would throw unimplemented on iOS. That is possible on Android.

If you *replace* the existing functions (and the corresponding `check*` function) with these functions, you don't need the constants at all. To me this is a much more elegant solution, as it avoids the confusion with the constants, and either works identically on both platforms or doesn't work at all on one platform (like `selectCalendarsWithPrompt`).

> Both methods return Promise<void> and throw an error if unsuccessful

There are two choices:

- Return a boolean to indicate if the access was granted or denied, and throw an error if an actual error occurred; or

- Throw an error and put an enum string constant in the .data property of the error, which indicates what caused the error. CapacitorException supports a free-form .data object, which could be checked to figure out what the result was.

If you imagine the code to handle those cases, the first option seems much cleaner to me both from the perspective of the plugin code and the user's error handling code.

> i thought I try to match the defined permissions from the calendar by faking them

There is no need to force symmetry between calendar and reminder permissions. On the surface it seems to simplify matters, but if there is divergent behavior, in practice it will only complicate usage. I would propose defining separate functions that conform to the actual permission being requested (along the same lines as what I proposed for the calendar) and skip the constants.

**Comment by aparajita** [comment]
Here's an example of why the calendar constants are quite unfriendly. If I'm just interested in read/write access to the calendar, I have to do all of this:

```ts
// Check if the user has granted permission to read and write to the calendar.
export async function checkFullCalendarPermission(): Promise<PermissionState> {
  if (!Capacitor.isNativePlatform()) {
    return 'denied'
  }

  try {
    const { result } = await CapacitorCalendar.checkPermission({
      alias: PluginPermission.READ_CALENDAR,
    })

    // If read or write permission is denied, return 'denied' immediately.
    if (result === 'denied') {
      return 'denied'
    }

    const readPermission = result
    let writePermission: PermissionState

    // On iOS, READ_CALENDAR includes write permission.
    // On Android, we have to check write permission separately.
    if (Capacitor.getPlatform() === 'ios') {
      writePermission = readPermission
    } else {
      const { result: writeResult } = await CapacitorCalendar.checkPermission({
        alias: PluginPermission.WRITE_CALENDAR,
      })

      // If read or write permission is denied, return 'denied' immediately.
      if (writeResult === 'denied') {
        return 'denied'
      }

      writePermission = writeResult
    }

    // Resolve the permissions into a single permission state.
    // 'denied' has already been handled. At this point the permission
    // will either be 'granted' or 'prompt*'. 'prompt*' takes priority.
    if (readPermission.startsWith('prompt')) {
      return readPermission
    } else {
      return writePermission
    }
  } catch (error) {
    captureException(error)
    return 'denied'
  }
}
```

**Comment by ebarooni** [comment]
@aparajita I think its not a good idea to remove the constants at this point because it would be considered a breaking change. However, like we discussed I will implement the following methods:

- `requestWriteOnlyCalendarAccess `
- `requestReadOnlyCalendarAccess ` (Android only)
- `requestFullCalendarAccess`
- `requestFullRemindersAccess`

But instead of returning true or false like you suggested, I would return `PermissionState` which is almost used everywhere. I believe a boolean would not be sufficient to cover all the possibilities.

**Comment by aparajita** [comment]
> I think its not a good idea to remove the constants at this point because it would be considered a breaking change

You could deprecate them.

> But instead of returning true or false like you suggested, I would return PermissionState which is almost used everywhere

Makes sense. Better than throwing.
