### ISSUE TITLE
Canceling system prompts throws an error

### ISSUE THREAD

**Issue by aparajita** [ebarooni/capacitor-calendar#69]
Currently, canceling the system prompt shown by `createEventWithPrompt()` throws an error, as does `selectCalendarsWithPrompt(...)`.

This requires us to examine the error message to determine if an actual error occurred or if the user just canceled the prompt, which is not really an error. Relying on the exact text of an error message is brittle, as it locks you into those exact messages; any change to those messages in the future will be a potentially breaking change. That's why APIs typically provide either an error class hierarchy or error codes with which to differentiate error types.

Instead of throwing an error on cancelation, both functions could just return `null`. Semantically that's easy to understand, a stable value, and easy to check in code.

**Comment by ebarooni** [comment]
@aparajita The capacitor docs prefers undefined over null values. I understand your point of view and it completely makes sense.

How about returning an empty array in case of cancellation? Because in both methods having an empty array would essentially indicate that the user did not create an event (or did not select any calendars). I prefer this over returning null or undefined. What do you say?
