### ISSUE TITLE
Bug: thrown errors should put the error message in msg, not code

### ISSUE THREAD

**Issue by aparajita** [ebarooni/capacitor-calendar#85]
When you call `reject()` in native code, Capacitor throws an instance of `CapacitorException` which is defined as:

```ts
export declare class CapacitorException extends Error {
    readonly message: string;
    readonly code?: ExceptionCode;
    readonly data?: ExceptionData;
    constructor(message: string, code?: ExceptionCode, data?: ExceptionData);
}
```

`ExceptionCode` is defined as:

```ts
export declare enum ExceptionCode {
    /**
     * API is not implemented.
     *
     * This usually means the API can't be used because it is not implemented for
     * the current platform.
     */
    Unimplemented = "UNIMPLEMENTED",
    /**
     * API is not available.
     *
     * This means the API can't be used right now because:
     *   - it is currently missing a prerequisite, such as network connectivity
     *   - it requires a particular platform or browser version
     */
    Unavailable = "UNAVAILABLE"
}
```

On iOS you are correctly passing the message as the first parameter to `reject()`. On Android, for some reason you are passing the message as the second parameter, which from a typing standpoint isn't correct.

**Comment by aparajita** [comment]
I will include this fix in my PR for #81.

**Comment by ebarooni** [comment]
@aparajita I was actually still thinking on this. I know the issue but for some reason i noticed when passing the message as the first parameter, it gets excluded on android when i log the message in typescript. 

Do you have recommendations on a good practice of defining a system of error codes and messages to be throw on both android and ios side? I want to unify both ios and android in terms of throwing exceptions with a specific code and message which would represent a specific error. With definitions in typescript so that devs can rely on the code and act on the thrown exceptions.

**Comment by aparajita** [comment]
I did everything in my overhaul branch, including logging correctly. Take a look there.
